jackal:
  task_and_robot_environment_name: 'JackalMaze-v0'
  ros_ws_abspath: '/home/danny/jackal_ws'
  
  alpha: 0.1
  gamma: 0.7
  epsilon: 0.9
  epsilon_discount: 0.999
  nepisodes: 500
  nsteps: 10000
  running_step: 0.06 #time for each step
